fix: bug llevar armadura
AnimaBeyondDevelop/AnimaBeyondFoundry pull request #182
Opened 2023-10-12 14:22 UTC by JulenBordonaba

Los penalizadores por llevar armadura se estaban aplicando de manera incorrecta. Se ha corregido el cálculo del penalizador natural y se ha separado en penalizador natural, modificador a acciones físicas y penalizador a la percepción (en caso de los cascos)

2023-12-13 19:01 UTC, Eryx5502 requested changes
En general me parece que los cambios a la hora de calcular los modificadores/penalizadores hacen que el sistema sea más claro! Aunque creo que el objetivo final de esto quizás tendría que ser implementar todo eso con ActiveEffects, con el sistema de modificadores, que así sería más fácil ver de dónde vienen los distintos penalizadores y también "saltárselos" si tienes razones para ello. Un par de comentarios finales:
- Has añadido la opción para desactivar que se aplique el cansancio automáticamente! Casi lo paso por alto.
- Mudarnos a Javascript (con JSDoc si os parece bien) está en el punto de mira porque los tipos de TS ya no los están manteniendo activamente... Así que convertiría todos los archivos `.ts` que hay en esta PR a `.js`.
- No he revisado los `.hbs`. Si todo va bien pronto cambiarán a `.svelte`, y además los fallos en ellos se ven "fácilmente".
- Habría que añadir las nuevas funcionalidades al testeo en el excel que está haciendo @paiva92 (incluir la opción de autocalcular el penalizador por cansancio)

2024-01-16 21:04 UTC, Eryx5502 approved these changes

2024-02-03 20:05 UTC, paiva92 requested changes
Buenas, estuve revisando algunas cosita del código que me parece merecen la pena cambiar

2024-02-05 16:11 UTC, Eryx5502 commented
Copio el [mensaje de discord](https://discord.com/channels/327226685399367680/817351986852003840/1197582383076098088) (de @JulenBordonaba) sobre el testeo de esta rama para tenerlo a mano:

> ⚠️ Es necesario que el penalizador natural / penalizador a la percepción (y los penalizadores en general) sean negativos, ya que si no son tomados 0.

### Penalizador a acciones físicas
- Aplica cuando el requisito de la suma de las armaduras es mayor que la habilidad de llevar armadura del personaje.
- El valor del penalizador es igual a la diferencia entre el requisito total y la habilidad del personaje. 
>Requisito total: 50
>Habilidad de llevar armadura: 30
>Penalizador a acciones físicas = -20
- Aplica a las secundarias que dependan de características físicas (aplica a más cosas, pero lo que se corrigió fueron las secundarias a las que se aplicaba)

### Penalizador natural
- Los puntos de Llevar Armadura que tenga por encima del requerimiento necesario reducirán su penalizador natural en una cantidad equivalente.
>Requisito: 50
>Habilidad de llevar armadura: 75
>Penalizador natural: -30
>Penalizador natural aplicado = -5
- Aplica a acrobacias, atletismo, nadar, trepar, saltar, proezas de fuerza, ocultarse, sigilo y baile. 
  - El penalizador natural a nadar no se puede reducir, en el ejemplo de antes sería 30.
  - El penalizador natural de sigilo solo se puede reducir hasta la mitad del penalizador natural de la armadura, en el ejemplo de antes se reducirías hasta 15.
- Si se lleva más de una capa de armadura se aplica un -20 de penalizador a toda acción por cada capa adicional y no se puede reducir con llevar armadura.

### Penalizador a la percepción
- Aplica a Advertir y buscar
- No se reduce con llevar armadura
- Solo existe en yelmos

### Penalizador a acciones físicas
- Aplica cuando el requisito de la suma de las armaduras es mayor que la habilidad de llevar armadura del personaje.
- El valor del penalizador es igual a la diferencia entre el requisito total y la habilidad del personaje. 
>Requisito total: 50
>Habilidad de llevar armadura: 30
>Penalizador a acciones físicas = -20
- Aplica a las secundarias que dependan de características físicas (aplica a más cosas, pero lo que se corrigió fueron las secundarias a las que se aplicaba)

### Penalizador natural
- Los puntos de Llevar Armadura que tenga por encima del requerimiento necesario reducirán su penalizador natural en una cantidad equivalente.
Requisito: 50
>Habilidad de llevar armadura: 75
>Penalizador natural: -30
>Penalizador natural aplicado = -5
- Aplica a acrobacias, atletismo, nadar, trepar, saltar, proezas de fuerza, ocultarse, sigilo y baile. 
  - El penalizador natural a nadar no se puede reducir, en el ejemplo de antes sería 30.
  - El penalizador natural de sigilo solo se puede reducir hasta la mitad del penalizador natural de la armadura, en el ejemplo de antes se reducirías hasta -15.
- Si se lleva más de una capa de armadura se aplica un -20 de penalizador a toda acción por cada capa adicional y no se puede reducir con llevar armadura.

### Penalizador a la percepción
- Aplica a Advertir y buscar
- No se reduce con llevar armadura
- Solo existe en yelmos

2024-02-05 16:55 UTC, Eryx5502 requested changes

2024-02-05 16:55 UTC, Eryx5502 commented on src/module/actor/utils/prepareActor/calculations/actor/mutateInitiative.ts
> +  console.log(naturalPenaltyMod);
```suggestion
```

2024-02-05 16:55 UTC, Eryx5502 commented on src/module/actor/utils/prepareActor/calculations/actor/mutateInitiative.ts
> +  console.log(penalty);
```suggestion
```

2024-02-07 12:11 UTC, Eryx5502 commented on src/module/actor/utils/prepareActor/calculations/actor/modifiers/mutateAllActionsModifier.js
He estado echando un ojo y sospecho que es para mantener por separado el \"input\" del usuario (lo que pones en el campo editable de la ficha) de el penalizador base que se puede calcular a partir de otras cosas (ej. el calculado por el cansancio). Creo que esto también lo hizo Linkaynn en otras cosas (e.g. las armas). Pero que nos confirme @JulenBordonaba.

2024-02-13 20:36 UTC, Eryx5502 approved these changes

2024-02-13 20:41 UTC, merged