Develop/new combat automation
AnimaBeyondDevelop/AnimaBeyondFoundry pull request #195
Opened 2024-04-06 21:08 UTC by paiva92

Se agrega el control de Grados de Hechizos que pueden ser lanzados.
En caso de elegir la opción a de Override, se puede elegir cualquier grado de hechizo.

Se cambian los argumentos enviado al Macro de Combate para que sean los mismos que en la rama de ataque en área.

Se arreglan issues que presentaron los testeos.

2024-04-08 18:47 UTC, Eryx5502 requested changes
Tengo sólo algunos comentarios menores. Diría de mergear con los pocos cambios que comento a pesar de que hay bastante código duplicado en los archivos `CombatAttackDialog.js` y `CombatDefenseDialog.js`, ya que para resolver estos quizá habría que refactorizar bastante las correspondientes clases. Como queremos hacer el cambio a svelte pronto, podemos aprovechar los cambios que van a ser necesarios para cambiar a svelte para hacer esta refatorización en lugar de hacer dos refactorizaciones distintas. No sé qué pensáis los demás...

2024-04-08 18:47 UTC, Eryx5502 commented on src/module/types/combat/SupernaturalShieldItemConfig.js
> +      spellCasting.casted = { innate, prepared };
Para qué sobreescribimos el `spellCasting.casted` con los valores que teníamos antes de evaluar `actor.mysticCanCastEvaluate(...)`?

2024-04-08 18:47 UTC, Eryx5502 commented on src/module/utils/functions/executeMacro.js
>   * It is delay so the animation does not start at the same time that the combat dialog closes.
```suggestion
 * It is delayed so the animation does not start at the same time that the combat dialog closes.
```

2024-04-08 18:47 UTC, Eryx5502 commented on src/module/utils/functions/executeMacro.js
> +  );
Esto sólo se usa si `args.shieldID` es 'truthy', por lo que no tiene sentido definir esta variable aquí si no se va a usar. Movería todas estas líneas a dentro del if de la línea 22.
Por otro lado: por qué se trata diferente el caso de los escudos místicos del resto?

2024-04-10 09:24 UTC, paiva92 commented on src/module/combat/utils/damageCheck.js
Para evitar tomar los daños que sean Daño Automático 60.
Al no hacer match con la t que está entre medio del daño y el valor evitamos tomar esos valores.
El daño automático solo se tiene que aplicar cuando se cumple una condición, por lo que no es un daño de combate que varie según la tirada de dados.
En breve subo la versión que desestima lo del punto.

2024-04-10 09:30 UTC, paiva92 commented on src/module/utils/functions/executeMacro.js
> +  );
Ya hice el cambio.
Para los casos que no exista el Macro, normalmente no ejecuta ningún macro.
En caso de los escudos está bueno tener un Macro por Defecto, para que siempre haya una animación base.
En conclusión si no hay un Macro definido para el Escudo, entonces ejecuta el Macro por Defecto para los escudos.
A los Macros de Escudos se les envía argumentos para saber si tiene que poner el escudo o si tiene que quitar la animación, para los casos donde te rompan o te quites el escudo.

2024-04-10 09:30 UTC, paiva92 commented on src/module/utils/functions/executeMacro.js
>   * It is delay so the animation does not start at the same time that the combat dialog closes.
Listo

2024-04-10 09:32 UTC, Eryx5502 commented on src/module/combat/utils/damageCheck.js
Pero sí queremos coger otras palabras que estén detrás de daño pero que no sean "Automático"? Porque sólo queremos hacer match a `Daño XXX` donde las X son números, bastaría hacer `/Daño \d+/`, no?

2024-04-10 09:35 UTC, Eryx5502 commented on src/module/utils/functions/executeMacro.js
> +  );
Sí, lo que quiero decir es que también hay macro por defecto para ataques cuerpo a cuerpo y ataques a distancia. Pero esos creo que se llamaban desde el código del diálogo del combate o algo así. Creo que sería mejor tratar todos los "macros por defecto" de la misma manera y tener el código en el mismo sitio (además, quizá pueda eliminarse parte de la duplicación de código haciendo eso (el código para obtener la macro por defecto es el mismo para los distintos casos, no sé si me explico).

2024-04-10 09:36 UTC, paiva92 commented on src/module/types/combat/SupernaturalShieldItemConfig.js
> +      spellCasting.casted = { innate, prepared };
El dialogo que se abre al crear un nuevo escudo no tiene un getData, por lo tanto no actualiza la opciones de si es posible o no lanzar el escudo de Forma Innata, con un hechizo Preparado o con Zeon Acumulado.
El método ``actor.mysticCanCastEvaluate(...)`` cambia los valores de ``spellCasting.casted``, pero estos valores son la selección del usuario que luego tenemos que evaluar con el método ``actor.evaluateCast(spellCasting)``

2024-04-10 09:56 UTC, Eryx5502 commented on src/module/combat/utils/damageCheck.js
Pero si sólo nos importa coger `Daño [cualquier número de espacios] [números]`, no bastaría con hacer `/Daño *\d+/`?

2024-04-10 10:25 UTC, paiva92 commented on src/module/utils/functions/executeMacro.js
> +  );
Listo, ya lo refactoricé. Quedó mucho mejor ahora, lo podes ver en el ``commit`` que empieza con ``refactor``

2024-04-10 10:28 UTC, paiva92 commented on src/module/combat/utils/damageCheck.js
Listo ya lo cambié. Igual falta el caso de que no haya espacios, pero es lo mismo.
Estuve revisando y no encontré esa casuística, así que todo Ok.

2024-04-10 10:31 UTC, Eryx5502 commented on src/module/combat/utils/damageCheck.js
No, ese problema no está, porque ` *` quiere decir "0 o más espacios"! :D

2024-04-10 11:20 UTC, paiva92 commented on src/module/combat/utils/damageCheck.js
Estuve testeando y me dio error con un caso:
``Daño base 80``

Ahora recuerdo por qué lo había hecho de esa forma jeje.
Se te ocurre otra manera más fácil de entender sin la "t" entre medio?

2024-04-10 11:50 UTC, Eryx5502 commented on src/module/combat/utils/damageCheck.js
Oh, vaya... Depende de si lo que queremos es impedir que coja "Daño automático 80" o si queremos que coja "Daño [cualquier número de espacios] XXX" y también "Daño [cualquier número de espacios] base [cualquier número de espacios] XXX".

Diría que es más preciso lo segundo, porque el que está puesto ahora mismo [es bastante permisivo](https://regex101.com/r/OaxJvQ/1): 
![imagen](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/assets/32964371/82dbd199-5e93-4076-b8b0-d38b5bd6123b)

Yo apostaría entonces por algo más en plan `/Daño *(base)* *\d+/` [o modificaciones si hay que encontrar algunas palabras más](https://regex101.com/r/ePbjf8/1).

2024-04-10 14:15 UTC, paiva92 commented on src/module/combat/utils/damageCheck.js
Listo, fui por la opción 2.
De paso refactoricé el resto de expresiones regulares que las hice al principio de todo y estaban bien feas jaja.
Lo podes ver en el commit ``refactor - regular expressions``

2024-04-11 18:47 UTC, Eryx5502 commented on src/module/combat/utils/resistanceEffectCheck.js
> +      let afterResistance = new RegExp(`${resistances[key]} *o* *[RFEVMP]{0,2} *\\d+`, 'i')
Puede que no esté entendiendo bien las expresiones regulares, pero creo que estas no funcionan. Hacen match con demasiadas cosas:
![imagen](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/assets/32964371/262ff239-f202-4134-a796-da705e1359b1)
Qué clase de patrones queremos encontrar? Cosas tipo `RF 80` o `RF 90 o RP 70`? O hay algún caso más?

2024-04-11 19:16 UTC, paiva92 commented on src/module/combat/utils/resistanceEffectCheck.js
> +      let afterResistance = new RegExp(`${resistances[key]} *o* *[RFEVMP]{0,2} *\\d+`, 'i')
En la prueba que estás haciendo no tenes que poner un tipo de resistencia ${resistances[key]}
Quedaría así: ``\d+ *[RFEVMP]{0,2} *o* *RP``

2024-04-14 12:41 UTC, Eryx5502 commented on src/module/combat/utils/resistanceEffectCheck.js
> +      let afterResistance = new RegExp(`${resistances[key]} *o* *[RFEVMP]{0,2} *\\d+`, 'i')
Bueno, seguro que se puede optimizar pero creo que probablemente no merece la pena, teniendo en cuenta que vamos a quitar las expresiones regulares tan pronto como podamos, introduciendo los datos en cada hechizo / poder.

2024-05-07 07:26 UTC, merged