Feature/custom import with svelte
AnimaBeyondDevelop/AnimaBeyondFoundry pull request #229
Opened 2024-10-19 02:14 UTC by JulenBordonaba

2024-11-02 21:09 UTC, Eryx5502 requested changes
Además de los comentarios que he dejado, creo que deberíamos intentar refactorizar de alguna manera el código que parsea los datos del excel al actor. Es bastante grande y quizá un poco repetitivo... Pero tampoco me he puesto a pensar cómo podría mejorarse. Si queréis, una vez que lo demás esté zanjado, podríamos mergear y trabajar para darle una mejor forma que nos permita añadir nuevos campos importados más fácilmente en el futuro.

2024-11-02 21:09 UTC, Eryx5502 commented on src/module/SidebarDirectories/ABFActorDirectory.js
En este archivo hay varios strings que se le muestran al usuario (tanto en el diálogo como a traves de `ui.warnings`. Sería chachi _localizarlos_ usando `game.i18n.format(...)` (o `game.i18n.localize(...)`).

2024-11-02 21:09 UTC, Eryx5502 commented on src/module/actor/utils/parseExcelToActor.js
> + * @param {any} excelData - provided exel data
Podemos dar algo más de estructura a este tipo?

2024-11-02 21:09 UTC, Eryx5502 commented on src/module/actor/utils/parseExcelToActor.js
> +      ui.notifications.warn(versionWarning);
Este string también se enseña al usuario, así que yo diría que lo suyo sería localizarlo.

2024-11-02 21:09 UTC, Eryx5502 commented on src/module/actor/utils/parseExcelToActor.js
Una cosa que no me gusta es que en este script se mezcla inglés y castellano. En principio, todo el código lo tenemos en inglés así que haría un esfuerzo para quitar el castellano. Igual es un poco tontería, y soy plenamente consciente de que esto es una opinión personal. Por lo tanto, si no estamos de acuerdo, deberíamos decidir en conjunto qué postura queremos tener como grupo al respecto.

2024-11-04 16:07 UTC, Miliviu commented on src/module/actor/utils/parseExcelToActor.js
Tras leerme todo el código para aportar en esto, creo que aquí se podría tener una excepción, la ficha está entera en español, que yo sepa no hay una versión en inglés de la ficha, y si la hay no es compatible con lo nuestro, todos los valores que hay en el excel están en español...

Creo que tener de forma general esa norma está bien, pero ya me dices que opinas de mantenerlo en español aquí, si es 100% necesario me puedo ocupar de tocar el código, pero lo que digo, va a quedar algo incluso más raruno en spanglish que lo que tenemos

2024-11-04 16:09 UTC, Miliviu commented on src/module/actor/utils/parseExcelToActor.js
> +      ui.notifications.warn(versionWarning);
Puedo localizar ese primer texto, pero la importación de jsons y movidas al juego no está localizada y eso es cosa de nuestros amigos de Foundry... así que quedaría un texto en spanglish o puedo simplemente dejar de utilizar el mismo código del resto de imports. 

Lo que veas

2024-11-04 16:12 UTC, Eryx5502 commented on src/module/actor/utils/parseExcelToActor.js
Convencido. Además, después de reflexionar un poco en ello... creo que no merece la pena el trabajo extra. Veremos si podemos librarnos del _spanglish_ en el futuro si llegamos a refactorizar.

2024-11-04 16:13 UTC, Miliviu commented on src/module/actor/utils/parseExcelToActor.js
> + * @param {any} excelData - provided exel data
Con lo titánica que es la función esta necesito que me concretes un pelín que queremos exactamente jdsjdsj

2024-11-04 16:13 UTC, Miliviu commented on src/templates/dialog/import-data-from-excel.html
> +    <input type="file" name="data" accept=".xlsm, .xslx, .xls, .csv" />
Me lo dejo pendiente de probar/testear, que si por alguna razón los aceptamos imagino que irá!

2024-11-04 16:17 UTC, Eryx5502 commented on src/module/actor/utils/parseExcelToActor.js
> +      ui.notifications.warn(versionWarning);
En este caso concreto, creo que todo el texto es nuestro.

Yo apostaría por localizarlo nosotros. Creo que @paiva92 ha hecho algo parecido para mostrar un mensaje de error con `ui.notifications.warn(...)` cuando en el combate intentas lanzar un hechizo y no tienes zeon acumulado suficiente. Me suena que allí está localizado así que aquí haría lo mismo.

2024-11-04 16:18 UTC, Miliviu commented on src/module/actor/utils/parseExcelToActor.js
> +      ui.notifications.warn(versionWarning);
Si, acabo de caer que justo este es nuestro, y en la rama que tenía tocando lo localicé, oops!

2024-11-04 16:20 UTC, Eryx5502 commented on src/module/SidebarDirectories/ABFActorDirectory.js
Diría de usar un código distinto al de la importación y usar nuestros propios strings de localización para poder traducir todo el mensaje. Pero si da quebraderos de cabeza (el título de la ventana quizá) por algún motivo en el que no caigo ahora mismo, no pierdas tiempo con ello.

2024-11-04 16:21 UTC, Miliviu commented on src/module/SidebarDirectories/ABFActorDirectory.js
Lo veo guay, me daba un poco de cosa el alejarnos de la implementación de Foundry, pero no me puedo imaginar como nos puede venir esto a morder en el futuro.

2024-11-04 16:23 UTC, Eryx5502 commented on src/module/actor/utils/parseExcelToActor.js
> + * @param {any} excelData - provided exel data
Perdón. No recuerdo bien la estructura que tienen los datos en `excelData`, pero creo que era algo tipo Record<string, ...>. Cuanto más específico sea le tipo mejor, porque recuerdo que activando checkJS en el `jsconfig.json` salían errores de tipo que podrían arreglarse especificando algo más concreto. No sé si me explico; si no, luego cuando vuelva a casa le echo un ojo y trato de ser más explícito.

2024-11-04 16:24 UTC, Eryx5502 commented on src/module/SidebarDirectories/ABFActorDirectory.js
Como es un importador externo, adaptado a nuestra ficha de excel, no creo que haya problema por alejarse del de foundry (que es sólo para json). Espero no arrepentirme en el futuro de haber dicho esto 😂

2024-11-07 11:48 UTC, Eryx5502 commented on src/module/actor/utils/parseExcelToActor.js
> + * @param {any} excelData - provided exel data
Siguiendo la conversación en discord ([este mensaje](https://discord.com/channels/327226685399367680/817351986852003840/1304044012398706741) y siguientes), bastaría con el tipo
`Record<string,(string|boolean|number)>`.

2024-11-07 11:56 UTC, Eryx5502 commented on src/templates/dialog/import-data-from-excel.html
> +    <input type="file" name="data" accept=".xlsm, .xslx, .xls, .csv" />
[Confirma @JulenBordonaba que no.](https://discord.com/channels/327226685399367680/817351986852003840/1304050989287870544)
```suggestion
    <input type="file" name="data" accept=".xlsm, .xslx, .xls" />
```

2024-11-07 21:56 UTC, Miliviu commented on src/module/actor/utils/parseExcelToActor.js
> + * @param {any} excelData - provided exel data
Errr, ando un poco perdido tras leer la conversación, si cualquier me puede tomar el relevo con esto mejor que mejor!

2024-11-07 21:56 UTC, Miliviu commented on src/templates/dialog/import-data-from-excel.html
> +    <input type="file" name="data" accept=".xlsm, .xslx, .xls, .csv" />
Como no puede ser, eliminado y tirando!

2024-11-07 21:57 UTC, Miliviu commented
Localización y el ajuste ese de importar CSVs metidos, si ves que falta algo avisa por aquí y lo hago en un minutillo, ty ty!

2024-11-07 22:19 UTC, Eryx5502 commented on src/module/actor/utils/parseExcelToActor.js
> + * @param {any} excelData - provided exel data
Normal. No tiene sentido lo que estaba proponiendo yo. No sólo no arregla muchos errores de tipado sino que aparecen nuevos. Así que de momento, hasta que tengamos un futuro refactor (si es que llega) que nos permita tener tipos mejores, no tiene sentido intentar arreglar los tipos aquí..

Marco la conversación como resuelta!

2024-11-07 22:38 UTC, Eryx5502 approved these changes
Listo! He hecho un par de cambios que se había quedado una parte del hint1 colgando, así que lo he añadido.

Por lo demás, por mi parte podemos mergear si habéis probado!

2024-11-07 22:44 UTC, Miliviu commented
> Listo! He hecho un par de cambios que se había quedado una parte del hint1 colgando, así que lo he añadido.
> 
> Por lo demás, por mi parte podemos mergear si habéis probado!

Ooops, gracias :>


Por mi parte, tras probarlo va perfecto, lo que veais.

2024-11-08 12:08 UTC, merged